# Generated by Django 3.1 on 2020-08-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='about',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='homepage',
        ),
        migrations.AddField(
            model_name='myuser',
            name='apt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
